### ISSUE TITLE
Filter products by size

### ISSUE THREAD

**Issue by marcushohlbein** [marcushohlbein/capstone-project#12]
## Value statement

**user** can **filter products by size**

## Acceptance criteria

- [ ] dropdown field with available sizes
- [ ] ability to select more than one size
- [ ] filter appear in the url

## Tasks

- [x] create feature branch
- [ ] setup storybook
- [ ] add filter component
- [ ] adjust routes to accept url query param
- [ ] testing

## Complexity

medium / high
