### ISSUE TITLE
header component

### ISSUE THREAD

**Issue by marcushohlbein** [marcushohlbein/capstone-project#2]
## Value Statement

Header bar with logo and search

## Description (Text, Scribble, Wireframe, Design)

![Header](https://user-images.githubusercontent.com/21499846/110112940-a886f680-7db2-11eb-82e3-0fd015fe57be.png)

## Acceptance criteria

- [x] always shown at the top of the page

## Tasks

- [x] create feature branch
- [x] create component in storybook
- [x] write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add missing styles

## Complexity
medium

**Comment by marcushohlbein** [comment]
## Value Statement

Header bar with logo and search

## Description (Text, Scribble, Wireframe, Design)

![Header](https://user-images.githubusercontent.com/21499846/110112940-a886f680-7db2-11eb-82e3-0fd015fe57be.png)

## Acceptance criteria

- [ ] always shown at the top of the page
- [ ] allow user to search from anywhere
- [ ] link back to home page

## Tasks

- [ ] create feature branch
- [ ] create component in storybook
- [ ] write component tests
- [ ] Add components to app (feature implementation with state)
- [ ] Add missing styles

## Complexity
medium
