### ISSUE TITLE
product listing

### ISSUE THREAD

**Issue by marcushohlbein** [marcushohlbein/capstone-project#3]
## Value statement
a page where products are listed

## Description (Text, Scribble, Wireframe, Design)

**Users** have a **Product overview** and can scroll down to see more.

![User Story 1](https://user-images.githubusercontent.com/21499846/110123654-75982f00-7dc1-11eb-921d-ab7ae2254269.png)
 
## Acceptance criteria

- [x] show user available products
- [x] scroll down

## Tasks

- [x] create feature branch
- [x] create component in storybook
- [x] write component tests
- [x] Add components to app (feature implementation with state)
- [x] Add styles

## Complexity
medium / complex
