### ISSUE TITLE
product details

### ISSUE THREAD

**Issue by marcushohlbein** [marcushohlbein/capstone-project#4]
## Value statement
a page that show product details and infomations of shop where it's available

## Description (Text, Scribble, Wireframe, Design)

**Users** can see **product details** and can **choose a shop** to buy

![User Story 2](https://user-images.githubusercontent.com/21499846/110127597-1ab50680-7dc6-11eb-96eb-678351300a42.png)

## Acceptance criteria

- show product details
- shop with the product are listed
- link from productlisting page to clicked productdetail page
- link to the shop/product to buy it

## Tasks

- [x] create feature branch

**Button**
- [x] create button component in storybook
- [x] write button component tests
- [x] Add styles
- [x] Add components to app (feature implementation with state)

**ShopListItem**
- [x] create button component in storybook
- [x] write shoplistitem component tests
- [x] Add styles
- [x] Add components to app (feature implementation with state)

**Router**
- [x] add react-router to prject
- [x] implement routing from productlisting to productdetails
- [x] write shoplistitem component tests
- 
## Complexity
high
