### ISSUE TITLE
backend

### ISSUE THREAD

**Issue by marcushohlbein** [marcushohlbein/capstone-project#8]
## Value statement

user get content from a cloud mongodb

## Acceptance criteria

- [x] data is fetched from a mongodb
- [x] api requests for different actions and models (get, post, patch)
- [x] matching merchant_products with products

## Tasks

- [x] create feature branch
- [x] install express.js, mongoose, dotenv
- [x] write server.js
- [x] setup and init mongodb atlas
- [x] create 2 models (e.g. merchant_prodcut, products)
- [x] setup routes fror each model
- [x] testing components

## Complexity

high
